# The curve25519-dalek crate uses the `simd` backend by default in v4 if
# possible, which has very slow performance on some platforms with opt-level 0,
# which is the default for `dev` and `test` builds. This slowdown causes
# certain interactions in the solana-test-validator, such as verifying ZK
# proofs in transactions, to take much more than 400ms, creating problems in
# the test environment. To give better performance in the solana-test-validator
# during tests and dev builds, override the opt-level to 3 for the crate.
[profile.dev.package.curve25519-dalek]
opt-level = 3

[workspace]
resolver = "2"
members = [
  "clients/cli",
  #"clients/rust", omitted from workspace until a real client is generated
  "clients/rust-legacy",
  "confidential-transfer/ciphertext-arithmetic",
  "confidential-transfer/elgamal-registry",
  "confidential-transfer/proof-extraction",
  "confidential-transfer/proof-generation",
  "confidential-transfer/proof-tests",
  "program",
]

[workspace.package]
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
repository = "https://github.com/solana-program/token-2022"
homepage = "https://solana-program.com"
license = "Apache-2.0"
edition = "2021"

[workspace.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(target_os, values("solana"))',
    'cfg(feature, values("frozen-abi", "no-entrypoint"))',
]

[workspace.metadata.cli]
solana = "2.1.0"

# Specify Rust toolchains for rustfmt, clippy, and build.
# Any unprovided toolchains default to stable.
[workspace.metadata.toolchains]
format = "nightly-2024-08-08"
lint = "nightly-2024-08-08"

[workspace.metadata.spellcheck]
config = "scripts/spellcheck.toml"

[workspace.metadata.release]
pre-release-commit-message = "Publish {{crate_name}} v{{version}}"
tag-message = "Publish {{crate_name}} v{{version}}"
consolidate-commits = false

[patch.crates-io]
# solana-sdk
solana-program = { path = "../solana-sdk/program" }
solana-decode-error= { path = "../solana-sdk/decode-error" }
solana-clock = { path = "../solana-sdk/clock" }
solana-cpi = { path = "../solana-sdk/cpi" }
solana-frozen-abi = { path = "../solana-sdk/frozen-abi" }
solana-frozen-abi-macro = { path = "../solana-sdk/frozen-abi-macro" }
solana-instruction = { path = "../solana-sdk/instruction" }
solana-program-error = { path = "../solana-sdk/program-error" }
solana-pubkey = { path = "../solana-sdk/pubkey" }
solana-sysvar-id = { path = "../solana-sdk/sysvar-id" }
solana-borsh = { path = "../solana-sdk/borsh" }
solana-feature-set = { path = "../solana-sdk/feature-set" }
solana-loader-v3-interface = { path = "../solana-sdk/loader-v3-interface" }
solana-loader-v4-interface = { path = "../solana-sdk/loader-v4-interface" }
solana-account = { path = "../solana-sdk/account" }
solana-account-info = { path = "../solana-sdk/account-info" }
solana-bincode = { path = "../solana-sdk/bincode" }
solana-client-traits = { path = "../solana-sdk/client-traits" }
solana-cluster-type = { path = "../solana-sdk/cluster-type" }
solana-commitment-config = { path = "../solana-sdk/commitment-config" }
solana-epoch-info = { path = "../solana-sdk/epoch-info" }
solana-epoch-schedule = { path = "../solana-sdk/epoch-schedule" }
solana-example-mocks = { path = "../solana-sdk/example-mocks" }
solana-feature-gate-interface = { path = "../solana-sdk/feature-gate-interface" }
solana-fee-calculator = { path = "../solana-sdk/fee-calculator" }
solana-hash = { path = "../solana-sdk/hash" }
solana-inflation = { path = "../solana-sdk/inflation" }
solana-instructions-sysvar = { path = "../solana-sdk/instructions-sysvar" }
solana-keypair = { path = "../solana-sdk/keypair" }
solana-logger = { path = "../solana-sdk/logger" }
solana-message = { path = "../solana-sdk/message" }
solana-msg = { path = "../solana-sdk/msg" }
solana-nonce = { path = "../solana-sdk/nonce" }
solana-packet = { path = "../solana-sdk/packet" }
solana-program-entrypoint = { path = "../solana-sdk/program-entrypoint" }
solana-quic-definitions = { path = "../solana-sdk/quic-definitions" }
solana-rent = { path = "../solana-sdk/rent" }
solana-reward-info = { path = "../solana-sdk/reward-info" }
solana-sanitize = { path = "../solana-sdk/sanitize" }
solana-sdk = { path = "../solana-sdk/sdk" }
solana-sdk-ids = { path = "../solana-sdk/sdk-ids" }
solana-serde = { path = "../solana-sdk/serde" }
solana-serde-varint = { path = "../solana-sdk/serde-varint" }
solana-sha256-hasher = { path = "../solana-sdk/sha256-hasher" }
solana-short-vec = { path = "../solana-sdk/short-vec" }
solana-signature = { path = "../solana-sdk/signature" }
solana-signer = { path = "../solana-sdk/signer" }
solana-time-utils = { path = "../solana-sdk/time-utils" }
solana-transaction = { path = "../solana-sdk/transaction" }
solana-transaction-error = { path = "../solana-sdk/transaction-error" }
solana-epoch-rewards = { path = "../solana-sdk/epoch-rewards" }
solana-last-restart-slot = { path = "../solana-sdk/last-restart-slot" }
solana-slot-hashes = { path = "../solana-sdk/slot-hashes" }
solana-stable-layout = { path = "../solana-sdk/stable-layout" }
solana-sysvar = { path = "../solana-sdk/sysvar" }
solana-vote-interface = { path = "../solana-sdk/vote-interface" }
solana-big-mod-exp = { path = "../solana-sdk/big-mod-exp" }
solana-blake3-hasher = { path = "../solana-sdk/blake3-hasher" }
solana-bn254 = { path = "../solana-sdk/bn254" }
solana-keccak-hasher = { path = "../solana-sdk/keccak-hasher" }
solana-secp256k1-recover = { path = "../solana-sdk/secp256k1-recover" }
solana-fee-structure = { path = "../solana-sdk/fee-structure" }
solana-nonce-account = { path = "../solana-sdk/nonce-account" }
solana-rent-debits = { path = "../solana-sdk/rent-debits" }
solana-ed25519-program = { path = "../solana-sdk/ed25519-program" }
solana-precompile-error = { path = "../solana-sdk/precompile-error" }
solana-secp256k1-program = { path = "../solana-sdk/secp256k1-program" }
solana-secp256r1-program = { path = "../solana-sdk/secp256r1-program" }
solana-define-syscall = { path = "../solana-sdk/define-syscall" }
solana-compute-budget-interface = { path = "../solana-sdk/compute-budget-interface" }
solana-genesis-config = { path = "../solana-sdk/genesis-config" }
solana-native-token = { path = "../solana-sdk/native-token" }
solana-derivation-path = { path = "../solana-sdk/derivation-path" }
solana-seed-derivable = { path = "../solana-sdk/seed-derivable" }
solana-seed-phrase = { path = "../solana-sdk/seed-phrase" }
solana-program-memory = { path = "../solana-sdk/program-memory" }
solana-program-option = { path = "../solana-sdk/program-option" }
solana-program-pack = { path = "../solana-sdk/program-pack" }
jupnet-bls-sdk = { path = "../solana-sdk/bls-sdk" }
solana-slot-history = { path = "../solana-sdk/slot-history" }
solana-hard-forks = { path = "../solana-sdk/hard-forks" }
solana-poh-config = { path = "../solana-sdk/poh-config" }


# solana
solana-account-decoder =  { path = "../account-decoder" }
solana-client =  { path = "../client" }
solana-cli-output =  { path = "../cli-output" }
solana-test-validator =  { path = "../test-validator" }
solana-transaction-status =  { path = "../transaction-status" }
solana-program-test =  { path = "../program-test" }
solana-zk-sdk =  { path = "../zk-sdk" }
solana-inline-spl =  { path = "../inline-spl" }
solana-clap-v3-utils =  { path = "../clap-v3-utils" }
solana-cli-config =  { path = "../cli-config" }
solana-remote-wallet =  { path = "../remote-wallet" }
solana-banks-interface =  { path = "../banks-interface" }
solana-rpc-client =  { path = "../rpc-client" }
solana-rpc-client-api =  { path = "../rpc-client-api" }
solana-builtins = { path = "../builtins" }
solana-bpf-loader-program = { path = "../programs/bpf_loader" }
solana-transaction-context = { path = "../transaction-context" }
solana-svm-rent-collector = { path = "../svm-rent-collector" }

spl-transfer-hook-interface = { path = "../transfer-hook/interface" }
spl-associated-token-account = { path = "../associated-token-account/program" }
spl-token-2022 = { path = "./program" }
spl-token = { path = "../token/program" }
spl-pod = { path = "../libraries/pod" }


clone-solana-program = { path = "../../agave/solana-sdk/program" }
clone-solana-decode-error= { path = "../../agave/solana-sdk/decode-error" }
clone-solana-clock = { path = "../../agave/solana-sdk/clock" }
clone-solana-cpi = { path = "../../agave/solana-sdk/cpi" }
clone-solana-frozen-abi = { path = "../../agave/solana-sdk/frozen-abi" }
clone-solana-frozen-abi-macro = { path = "../../agave/solana-sdk/frozen-abi-macro" }
clone-solana-instruction = { path = "../../agave/solana-sdk/instruction" }
clone-solana-program-error = { path = "../../agave/solana-sdk/program-error" }
clone-solana-pubkey = { path = "../../agave/solana-sdk/pubkey" }
clone-solana-system-interface = { path = "../../agave/system/interface" }
clone-solana-sysvar-id = { path = "../../agave/solana-sdk/sysvar-id" }
clone-solana-borsh = { path = "../../agave/solana-sdk/borsh" }
clone-solana-config-program = { path = "../../agave/programs/config" }
clone-solana-feature-set = { path = "../../agave/solana-sdk/feature-set" }
clone-solana-program-runtime = { path = "../../agave/program-runtime" }
clone-solana-loader-v4-program = { path = "../../agave/programs/loader-v4" }
clone-solana-vote-program = { path = "../../agave/programs/vote" }
clone-solana-loader-v3-interface = { path = "../../agave/solana-sdk/loader-v3-interface" }
clone-solana-loader-v4-interface = { path = "../../agave/solana-sdk/loader-v4-interface" }
clone-solana-account = { path = "../../agave/solana-sdk/account" }
clone-solana-account-info = { path = "../../agave/solana-sdk/account-info" }
clone-solana-bincode = { path = "../../agave/solana-sdk/bincode" }
clone-solana-client = { path = "../../agave/client" }
clone-solana-client-traits = { path = "../../agave/solana-sdk/client-traits" }
clone-solana-cluster-type = { path = "../../agave/solana-sdk/cluster-type" }
clone-solana-commitment-config = { path = "../../agave/solana-sdk/commitment-config" }
clone-solana-epoch-info = { path = "../../agave/solana-sdk/epoch-info" }
clone-solana-epoch-schedule = { path = "../../agave/solana-sdk/epoch-schedule" }
clone-solana-example-mocks = { path = "../../agave/solana-sdk/example-mocks" }
clone-solana-feature-gate-interface = { path = "../../agave/solana-sdk/feature-gate-interface" }
clone-solana-fee-calculator = { path = "../../agave/solana-sdk/fee-calculator" }
clone-solana-hash = { path = "../../agave/solana-sdk/hash" }
clone-solana-inflation = { path = "../../agave/solana-sdk/inflation" }
clone-solana-instructions-sysvar = { path = "../../agave/solana-sdk/instructions-sysvar" }
clone-solana-keypair = { path = "../../agave/solana-sdk/keypair" }
clone-solana-logger = { path = "../../agave/solana-sdk/logger" }
clone-solana-message = { path = "../../agave/solana-sdk/message" }
clone-solana-msg = { path = "../../agave/solana-sdk/msg" }
clone-solana-nonce = { path = "../../agave/solana-sdk/nonce" }
clone-solana-packet = { path = "../../agave/solana-sdk/packet" }
clone-solana-program-entrypoint = { path = "../../agave/solana-sdk/program-entrypoint" }
clone-solana-quic-definitions = { path = "../../agave/solana-sdk/quic-definitions" }
clone-solana-rent = { path = "../../agave/solana-sdk/rent" }
clone-solana-reward-info = { path = "../../agave/solana-sdk/reward-info" }
clone-solana-rpc-client = { path = "../../agave/rpc-client" }
clone-solana-sanitize = { path = "../../agave/solana-sdk/sanitize" }
clone-solana-sdk = { path = "../../agave/solana-sdk/sdk" }
clone-solana-sdk-ids = { path = "../../agave/solana-sdk/sdk-ids" }
clone-solana-serde = { path = "../../agave/solana-sdk/serde" }
clone-solana-serde-varint = { path = "../../agave/solana-sdk/serde-varint" }
clone-solana-sha256-hasher = { path = "../../agave/solana-sdk/sha256-hasher" }
clone-solana-short-vec = { path = "../../agave/solana-sdk/short-vec" }
clone-solana-signature = { path = "../../agave/solana-sdk/signature" }
clone-solana-signer = { path = "../../agave/solana-sdk/signer" }
clone-solana-stake-interface = { path = "../../agave/stake/interface" }
clone-solana-system-client = { path = "../../agave/system/clients/rust" }
clone-solana-time-utils = { path = "../../agave/solana-sdk/time-utils" }
clone-solana-transaction = { path = "../../agave/solana-sdk/transaction" }
clone-solana-transaction-context = { path = "../../agave/transaction-context" }
clone-solana-transaction-error = { path = "../../agave/solana-sdk/transaction-error" }
clone-solana-program-test = { path = "../../agave/program-test" }
clone-solana-epoch-rewards = { path = "../../agave/solana-sdk/epoch-rewards" }
clone-solana-last-restart-slot = { path = "../../agave/solana-sdk/last-restart-slot" }
clone-solana-slot-hashes = { path = "../../agave/solana-sdk/slot-hashes" }
clone-solana-stable-layout = { path = "../../agave/solana-sdk/stable-layout" }
clone-solana-sysvar = { path = "../../agave/solana-sdk/sysvar" }
clone-solana-vote-interface = { path = "../../agave/solana-sdk/vote-interface" }
clone-solana-big-mod-exp = { path = "../../agave/solana-sdk/big-mod-exp" }
clone-solana-blake3-hasher = { path = "../../agave/solana-sdk/blake3-hasher" }
clone-solana-bn254 = { path = "../../agave/solana-sdk/bn254" }
clone-solana-keccak-hasher = { path = "../../agave/solana-sdk/keccak-hasher" }
clone-solana-secp256k1-recover = { path = "../../agave/solana-sdk/secp256k1-recover" }
clone-solana-fee-structure = { path = "../../agave/solana-sdk/fee-structure" }
clone-solana-nonce-account = { path = "../../agave/solana-sdk/nonce-account" }
clone-solana-rent-debits = { path = "../../agave/solana-sdk/rent-debits" }
clone-solana-ed25519-program = { path = "../../agave/solana-sdk/ed25519-program" }
clone-solana-precompile-error = { path = "../../agave/solana-sdk/precompile-error" }
clone-solana-secp256k1-program = { path = "../../agave/solana-sdk/secp256k1-program" }
clone-solana-secp256r1-program = { path = "../../agave/solana-sdk/secp256r1-program" }
clone-solana-define-syscall = { path = "../../agave/solana-sdk/define-syscall" }
clone-solana-compute-budget-interface = { path = "../../agave/solana-sdk/compute-budget-interface" }
clone-solana-genesis-config = { path = "../../agave/solana-sdk/genesis-config" }
clone-solana-native-token = { path = "../../agave/solana-sdk/native-token" }
clone-solana-derivation-path = { path = "../../agave/solana-sdk/derivation-path" }
clone-solana-seed-derivable = { path = "../../agave/solana-sdk/seed-derivable" }
clone-solana-seed-phrase = { path = "../../agave/solana-sdk/seed-phrase" }
clone-solana-program-memory = { path = "../../agave/solana-sdk/program-memory" }
clone-solana-program-option = { path = "../../agave/solana-sdk/program-option" }
clone-solana-program-pack = { path = "../../agave/solana-sdk/program-pack" }
clone-solana-account-decoder =  { path = "../../agave/account-decoder" }
clone-solana-clap-v3-utils = { path = "../../agave/clap-v3-utils" }
clone-solana-cli-config = { path = "../../agave/cli-config" }
clone-solana-cli-output = { path = "../../agave/cli-output" }
clone-solana-remote-wallet = { path = "../../agave/remote-wallet" }
clone-solana-transaction-status = { path = "../../agave/transaction-status" }
clone-solana-test-validator = { path = "../../agave/test-validator" }
clone-solana-zk-sdk = { path = "../../agave/zk-sdk" }
clone-solana-curve25519 = { path = "../../agave/curves/curve25519" }
clone-solana-banks-interface = { path = "../../agave/banks-interface" }
clone-solana-rpc-client-api = { path = "../../agave/rpc-client-api" }
clone-solana-slot-history = { path = "../../agave/solana-sdk/slot-history" }
clone-solana-presigner = { path = "../../agave/solana-sdk/presigner" }
clone-solana-offchain-message = { path = "../../agave/solana-sdk/offchain-message" }
clone-solana-loader-v2-interface = { path = "../../agave/solana-sdk/loader-v2-interface" }
clone-solana-poh-config = { path = "../../agave/solana-sdk/poh-config" }
clone-solana-shred-version = { path = "../../agave/solana-sdk/shred-version" }
clone-solana-system-transaction = { path = "../../agave/solana-sdk/system-transaction" }
clone-spl-pod = { path = "../../agave/libraries/pod" }
clone-spl-token = { path = "../../agave/token/program" }
clone-spl-token-2022 = { path = "../../agave/token-2022/program" }
clone-spl-memo = { path = "../../agave/memo/program" }

clone-spl-elgamal-registry = { path = "../../agave/token-2022/confidential-transfer/elgamal-registry" }
clone-spl-token-confidential-transfer-proof-extraction = { path = "../../agave/token-2022/confidential-transfer/proof-extraction" }
clone-spl-type-length-value = { path = "../../agave/libraries/type-length-value" }
clone-spl-token-metadata-interface = { path = "../../agave/token-metadata/interface" }
clone-spl-transfer-hook-interface = { path = "../../agave/transfer-hook/interface" }
clone-spl-record = { path = "../../agave/record/program" }
clone-spl-associated-token-account = { path = "../../agave/associated-token-account/program" }
clone-spl-associated-token-account-client = { path = "../../agave/associated-token-account/interface" }
clone-spl-token-group-interface = { path = "../../agave/token-group/interface" }
clone-spl-discriminator = { path = "../../agave/libraries/discriminator" }
clone-spl-tlv-account-resolution = { path = "../../agave/libraries/tlv-account-resolution" }

jupnet-alt-bn128-bls = { path = "../solana-sdk/alt-bn128-bls" }

